name: Manual Fastlane Build

on:
  workflow_dispatch:

jobs:
  verify-spm-build:
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_26.4.app


      - name: Run Fastlane build
        run: bundle exec fastlane verify_spm_build
